apiVersion: v1
kind: Service
metadata:
  labels:
    component: connect-service
  name: connect-service
spec:
  type: NodePort
  ports:
    - name: connect-port
      port: 8083
      nodePort: 30205
      targetPort: 8083
  selector:
    component: zookeeper
status:
  loadBalancer: {}
