apiVersion: v1
kind: Service
metadata:
  labels:
    component: backend-service
  name: backend-service
spec:
  type: LoadBalancer
  ports:
    - name: backend-port
      port: 8000
      nodePort: 32050
      targetPort: 8000
  selector:
    component: backend
status:
  loadBalancer: {}
