apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    component: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      component: zookeeper
  strategy: {}
  template:
    metadata:
      labels:
        component: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
      restartPolicy: Always
      serviceAccountName: ""
status: {}
