apiVersion: v1
kind: Service
metadata:
  labels:
    component: zookeeper-service
  name: zookeeper-service
spec:
  type: NodePort
  ports:
    - name: zookeeper-port
      port: 2181
      nodePort: 30101
      targetPort: 2181
  selector:
    component: zookeeper
status:
  loadBalancer: {}
