apiVersion: v1
kind: Service
metadata:
  labels:
    component: clustering-service
  name: clustering-service
spec:
  type: LoadBalancer
  ports:
    - name: clustering-port
      port: 8000
      nodePort: 32051
      targetPort: 8000
  selector:
    component: postclustering
status:
  loadBalancer: {}
