apiVersion: v1
kind: Service
metadata:
  labels:
    component: control-center-service
  name: control-center-service
spec:
  type: NodePort
  ports:
    - name: "control-center-port"
      port: 9021
      nodePort: 30201
      targetPort: 9021
    - name: "control-center-default-cluster"
      port: 8083
      nodePort: 30202
      targetPort: 8083
  selector:
    component: control-center
status:
  loadBalancer: {}
