apiVersion: v1
kind: Service
metadata:
  labels:
    component: kafka-service-external
  name: kafka-service-external
spec:
  type: NodePort
  ports:
    - name: kafka-external-port
      port: 30001
      nodePort: 30001
      targetPort: 30001
      protocol: TCP
    - name: kafka-external-port-2
      port: 30003
      nodePort: 30003
      targetPort: 30003
      protocol: TCP
  selector:
    component: kafka
status:
  loadBalancer: {}
