apiVersion: v1
kind: Service
metadata:
  labels:
    component: kafka-service-headless
  name: NodePort
spec:
  type: LoadBalancer
  ports:
    - name: kafka-service-headless
      port: 30000
      nodePort: 30000
      targetPort: 30000
      protocol: TCP
    - name: kafka-service-headless-2
      port: 30002
      nodePort: 30002
      targetPort: 30002
      protocol: TCP
  selector:
    component: kafka
status:
  loadBalancer: {}
