apiVersion: v1
kind: Service
metadata:
  labels:
    component: postgres-service
  name: postgres-service
spec:
  type: NodePort
  ports:
    - name: postgres-port
      port: 5432
      nodePort: 32000
      targetPort: 5432
  selector:
    component: postgres
status:
  loadBalancer: {}
